[package]
name = "messaging-provider-email"
edition.workspace = true
version = "0.5.1"
license.workspace = true
publish = false

[package.metadata.component]
package = "greentic:messaging-provider-email-core"

[package.metadata.component.target]
path = "wit/messaging-provider-email"
world = "component-v0-v6-v0"

[package.metadata.component.target.dependencies]
"greentic:http" = { path = "wit/messaging-provider-email/deps/http" }
"greentic:secrets-store" = { path = "wit/messaging-provider-email/deps/secrets-store" }
"greentic:interfaces-types" = { path = "wit/messaging-provider-email/deps/interfaces-types" }
"greentic:provider-schema-core" = { path = "wit/messaging-provider-email/deps/provider-schema-core.wit" }

[lib]
crate-type = ["cdylib"]

[dependencies]
base64.workspace = true
chrono.workspace = true
greentic-telemetry = { workspace = true }
greentic-types.workspace = true
provider-common.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2.workspace = true
urlencoding.workspace = true
wit-bindgen.workspace = true
