[package]
name = "greentic-messaging-cardkit"
edition.workspace = true
version.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
greentic-telemetry = { workspace = true }
messaging-cardkit-bin = { path = "../messaging-cardkit-bin" }
tokio.workspace = true
