[package]
name = "greentic-messaging-planned"
version = "1.1.1"
edition = "2024"

[dependencies]
base64 = { workspace = true }
greentic-messaging-renderer = { workspace = true }
greentic-telemetry = { workspace = true }
greentic-types = { workspace = true }
provider-common = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
